name: π’» κ°λ° νƒμ¤ν¬
description: μƒλ΅μ΄ κ°λ° νƒμ¤ν¬λ¥Ό μƒμ„±ν•κΈ° μ„ν• ν…ν”λ¦Ώμ…λ‹λ‹¤.
title: "[Task]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: μ‘μ—… λ‚΄μ©
      description: μν–‰ν•΄μ•Ό ν•  μ‘μ—…μ„ μƒμ„Έν μ„¤λ…ν•΄μ£Όμ„Έμ”.
      value: |
        # κ°λ° νƒμ¤ν¬

        ## μ‘μ—… λ‚΄μ©
        μν–‰ν•΄μ•Ό ν•  μ‘μ—…μ„ μƒμ„Έν μ„¤λ…ν•΄μ£Όμ„Έμ”.

        ## κµ¬ν„ μ‚¬ν•­
        - [ ] κµ¬ν„ ν•­λ© 1
        - [ ] κµ¬ν„ ν•­λ© 2

        ## μ°Έκ³  μ‚¬ν•­
        * μ¶”κ°€ μ„¤λ…μ΄λ‚ μ°Έκ³ ν•  λ‚΄μ©μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”
    validations:
      required: true
